### ISSUE TITLE
Running Local API error on loading seed data

### ISSUE THREAD

**Issue by thomas-nixon-baseline** [Baseline-JS/core#10]
When starting the API it fails with the following error
```
Error:
TypeError: (0 , import_core.setFeature) is not a function
    at /Users/me/my-app/node_modules/.pnpm/@aws-sdk+lib-dynamodb@3.666.0_@aws-sdk+client-dynamodb@3.533.0/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/index.js:147:36
    at /Users/me/my-app/node_modules/.pnpm/@aws-sdk+middleware-logger@3.533.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:28
    at /Users/me/my-app/node_modules/.pnpm/@aws-sdk+lib-dynamodb@3.666.0_@aws-sdk+client-dynamodb@3.533.0/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/index.js:341:24
    at _DynamoDBDocumentClient.send (/Users/me/my-app/node_modules/.pnpm/@smithy+smithy-client@3.4.0/node_modules/@smithy/smithy-client/dist-cjs/index.js:126:14)
    at /Users/me/my-app/node_modules/.pnpm/serverless-dynamodb@0.2.54/node_modules/serverless-dynamodb/dist/index.js:251:87
    at Timeout._onTimeout (/Users/me/my-app/node_modules/.pnpm/serverless-dynamodb@0.2.54/node_modules/serverless-dynamodb/dist/seeder.js:33:27)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
```
 
Can currently be patched by using a resolution, might not be ideal however.
`package.json`
```
  "resolutions": {
    "@aws-sdk/lib-dynamodb": "3.665.0"
  }
```

Looks like it is an issues with AWS SDK v3 https://github.com/aws/aws-sdk-js-v3/issues/6549

**Comment by thomas-nixon-baseline** [comment]
Fixed https://github.com/aws/aws-sdk-js-v3/pull/6557/files
